### This file is solely for testing purposes. It is not used in the application. ###


### api/users tests ###
### GET - GET USERS
GET http://localhost:3000/api/users
Content-Type: application/json

{
}

### POST - CREATE NEW USER
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "user2",
  "name": "user0",
  "password": "user0",
  "userImg": "ewq"
}

### PUT - UPDATE USER 1
PUT http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "user1234",
  "password": "user1234"
}
### PUT - UPDATE USER 2
PUT http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "user0",
  "password": "user2"
}
### PUT - UPDATE USER 3
PUT http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "ewqewqeqw",
  "password": "user2"
}


### DELETE - DELETE USER
DELETE http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "user2"
}

### api/tweets tests ###

### POST - CREATE NEW tweet
GET http://localhost:3000/api/tweets
Content-Type: application/json
{
}

### GET - GET ALL TWEETS
POST http://localhost:3000/api/tweets
Content-Type: application/json

{
  "id": "378",
  "author": "user2",
  "text": "tweet1"
}

### DELETE - DELETE tweet
DELETE http://localhost:3000/api/tweets
Content-Type: application/json

{
  "id": "378"
}

###
GET http://localhost:3000/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjIiLCJpYXQiOjE2ODEzMTM0MDcsImV4cCI6MTY4MTM5OTgwN30.cmHlVB96vrExiltRnrZSUFeeo1qYZ3o5fRrGt4oNow0

{
}

###
GET http://localhost:3000/api/auth/pwd
Content-Type: application/json

{
  "password": "admin"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "Tom123",
  "password": "user0"
}

###
DELETE http://localhost:3000/api/auth/logout
Content-Type: application/json

{
  "username": "user2",
  "admin": 1
}

###
POST http://localhost:3000/api/auth/refreshToken
Content-Type: application/json

{
  "username": "user2",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjIiLCJpYXQiOjE2ODEyMjI5Njd9.0tg0Qpzugdi0q3_L0TUleAfCFriSEU4vsXL7443m_vY"
}

###
PUT http://localhost:3000/api/users/privateChat
Content-Type: application/json

{
  "username": "user1234",
  "targetUsername": "user123"
}

###
POST http://localhost:3000/api/users/privateChat
Content-Type: application/json

{
  "message": "stfu, retard",
  "username": "user123",
  "targetUsername": "user1234"
}